# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_remove_student_student_ano'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_ID',
            new_name='lmsId',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='students_Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='subjects',
            old_name='subject_name',
            new_name='name',
        ),
    ]
