# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_auto_20170424_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='for75',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='for80',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='scholarship',
            field=models.BooleanField(default=True),
        ),
    ]
