# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-13 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_auto_20170428_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cur_sem',
            field=models.IntegerField(default=-1),
        ),
    ]
