# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-13 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_student_cur_sem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cur_sem',
            field=models.IntegerField(default=1),
        ),
    ]
